import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  designs: defineTable({
    name: v.string(),
    description: v.string(),
    imageStorageId: v.id("_storage"),        // main / sticker image
    shapePath: v.optional(v.string()),        // SVG clip-path string
    category: v.optional(v.string()),
    active: v.boolean(),

    // Which product types are offered for this design
    stickerEnabled: v.optional(v.boolean()),
    patchEnabled: v.optional(v.boolean()),
    embroideryEnabled: v.optional(v.boolean()),

    // Prices (cents)
    stickerPrice: v.number(),
    patchPrice: v.number(),
    embroideryPrice: v.optional(v.number()),      // Flat fee per placement (cents)
    fixedSize: v.optional(v.number()),            // % of clothing width for consistent canvas rendering
    fixedSizeOnly: v.boolean(),

    // Legacy fields — kept so existing documents don't fail validation
    embroideryStickerPrice: v.optional(v.number()),
    embroideryPriceLarge: v.optional(v.number()),
    embroideryPriceSmall: v.optional(v.number()),

    // Per-type images (sticker falls back to imageStorageId)
    patchImageStorageId: v.optional(v.id("_storage")),
    embroideryImageStorageId: v.optional(v.id("_storage")),

    // Per-type slideshow / mockup images
    mockupStorageIds: v.optional(v.array(v.id("_storage"))),           // legacy
    stickerMockupIds: v.optional(v.array(v.id("_storage"))),
    patchMockupIds: v.optional(v.array(v.id("_storage"))),
    embroideryMockupIds: v.optional(v.array(v.id("_storage"))),
  }).index("by_active", ["active"]),

  clothingItems: defineTable({
    name: v.string(),
    imageStorageId: v.optional(v.id("_storage")),        // old field for existing records
    frontImageStorageId: v.optional(v.id("_storage")),
    backImageStorageId: v.optional(v.id("_storage")),
    sideViews: v.optional(v.array(v.object({
      label: v.string(),
      storageId: v.id("_storage")
    }))),
    description: v.optional(v.string()),                 // Auto-generated by Gemini (includes hex color for smart prompting)
    availableSizes: v.optional(v.array(v.string())),     // e.g. ["S", "M", "L", "XL"]
    stock: v.optional(v.any()),                          // Record<string, number> e.g. { "S": 5, "M": 3 }
    basePrice: v.number(), // cents
    placements: v.array(v.object({
      id: v.string(),
      name: v.string(),
      type: v.optional(v.union(v.literal("main"), v.literal("logo"))),
      view: v.optional(v.string()),                      // "front" | "back" | custom label
      x: v.optional(v.number()),                         // 0.0 - 1.0 relative position
      y: v.optional(v.number()),
      defaultSize: v.optional(v.number()),               // % of clothing width
    })),
    active: v.boolean(),
  }).index("by_active", ["active"]),

  logoVariants: defineTable({
    type: v.union(v.literal("satin_outline"), v.literal("filled"), v.literal("patch_backed")),
    name: v.string(),
    imageStorageId: v.id("_storage"),
    price: v.number(), // cents, upcharge (0 if free)
    fixedSize: v.optional(v.number()), // % of clothing width
  }),

  savedDesigns: defineTable({
    clothingItemId: v.optional(v.id("clothingItems")),
    selectedSize: v.optional(v.string()),
    isCustomClothing: v.boolean(),
    customViews: v.optional(v.array(v.object({
      label: v.string(),
      storageId: v.id("_storage"),
    }))),
    placements: v.array(v.object({
      designId: v.id("designs"),
      view: v.string(),
      x: v.number(), y: v.number(),
      width: v.number(), height: v.number(),
    })),
    logoVariantId: v.optional(v.id("logoVariants")),
    logoPlacement: v.optional(v.object({
      view: v.string(),
      x: v.number(), y: v.number(),
      width: v.number(), height: v.number(),
    })),
    aiMockupIds: v.optional(v.object({
      front: v.optional(v.id("_storage")),
      back: v.optional(v.id("_storage")),
      // Can add sides here dynamically or in an array if necessary
    })),
    status: v.union(v.literal("draft"), v.literal("in_cart"), v.literal("ordered")),
    contactEmail: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]),

  carts: defineTable({
    token: v.string(),                           // random token, stored in cookie
    items: v.array(v.object({
      type: v.union(v.literal("custom"), v.literal("standalone")),
      savedDesignId: v.optional(v.id("savedDesigns")),
      standaloneProductId: v.optional(v.id("standaloneProducts")),
      quantity: v.number(),
    })),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_token", ["token"]),

  aiRenderCache: defineTable({
    configHash: v.string(),                      // clothingId + designId + x,y serialization
    imageStorageId: v.id("_storage"),
    createdAt: v.number(),
  }).index("by_hash", ["configHash"]),

  promptTemplates: defineTable({
    type: v.union(
      v.literal("sticker"),
      v.literal("sticker_embroidery"),
      v.literal("patch"),
      v.literal("embroidered"),
      v.literal("closeup"),
    ),
    name: v.string(),
    template: v.string(), // string with {variables}
    active: v.boolean(),
  }).index("by_type", ["type"]),

  standaloneProducts: defineTable({
    name: v.string(),
    description: v.string(),
    imageStorageIds: v.array(v.id("_storage")),
    price: v.number(), // cents
    type: v.union(
      v.literal("premade"),
      v.literal("bundle"),
      v.literal("limited"),
    ),
    bundleContents: v.optional(v.array(v.string())),
    quantity: v.number(), // stock count (total, or sum of sizes)
    // Per-size inventory for premade products (e.g. S/M/L/XL)
    sizeInventory: v.optional(v.array(v.object({
      size: v.string(),
      quantity: v.number(),
    }))),
    active: v.boolean(),
  }).index("by_active", ["active"]),

  orders: defineTable({
    email: v.string(),
    contactPhone: v.optional(v.string()),
    savedDesignSnapshot: v.optional(v.any()), // Immutable copy of the design config at checkout
    items: v.array(
      v.object({
        type: v.string(),
        designId: v.optional(v.id("designs")),
        clothingItemId: v.optional(v.id("clothingItems")),
        standaloneProductId: v.optional(v.id("standaloneProducts")),
        name: v.string(),
        quantity: v.number(),
        unitPrice: v.number(),
        size: v.optional(v.string()),
        placements: v.optional(
          v.array(v.object({ designId: v.id("designs"), size: v.string(), position: v.string() })),
        ),
        frontMockupId: v.optional(v.id("_storage")),
        backMockupId: v.optional(v.id("_storage")),
        frontPreviewId: v.optional(v.id("_storage")),
        backPreviewId: v.optional(v.id("_storage")),
        customNotes: v.optional(v.string()),
      }),
    ),
    total: v.number(), // cents
    shippingCost: v.number(), // cents
    shippingMethod: v.string(),
    deliveryType: v.union(v.literal("shipping"), v.literal("local_pickup")),
    stripeSessionId: v.optional(v.string()),
    stripePaymentIntentId: v.optional(v.string()),
    stripeReceiptUrl: v.optional(v.string()),
    adminNote: v.optional(v.string()), // Rejection reason or adjustment note
    status: v.union(
      v.literal("pending"),
      v.literal("abandoned"),          // Interrupted checkout with contact info
      v.literal("pending_approval"), // Waiting for Admin review
      v.literal("approved"),         // Admin approved
      v.literal("rejected"),         // Admin declined
      v.literal("paid"),             // Payment captured
      v.literal("fulfilled"),        // Shipped/Picked up
      v.literal("cancelled"),
    ),
    shippingAddress: v.optional(
      v.object({
        name: v.string(),
        line1: v.string(),
        line2: v.optional(v.string()),
        city: v.string(),
        state: v.string(),
        postalCode: v.string(),
        country: v.string(),
      }),
    ),
    createdAt: v.number(), // timestamp
  })
    .index("by_status", ["status"])
    .index("by_stripeSession", ["stripeSessionId"])
    .index("by_createdAt", ["createdAt"]),

  settings: defineTable({
    key: v.string(),
    value: v.string(),
  }).index("by_key", ["key"]),
});
