import type { Arrangement } from './types';

/**
 * Doxology - OLD 100TH (Louis Bourgeois, Genevan Psalter, 1551).
 * Text by Thomas Ken, 1695. Long Metre (88.88).
 *
 * EDITORIAL NOTE: both public editions of this tune are isorhythmic - every
 * note the same length - which is authentic Genevan psalm-tune style. Almost
 * nobody sings it that way. The last note of each line here is lengthened to
 * two beats, matching how modern hymnals print it and giving singers a breath.
 * That is a deliberate change from the source, not a transcription of it.
 * The Amen from the source edition is included, but lengthened from the printed
 * two half notes to half-plus-whole - the traditional hymnal shape, where the
 * plagal chord moves through and the tonic is left to ring.
 *
 * TRANSPOSED: the sources are in G. This is up a whole step, in A, chosen for
 * the four voices singing it - it lifts the lead out of the low D3-D4 range
 * where a male voice does not project outdoors, and the soprano's three notes
 * above B4 are all single beats, so the higher ceiling costs nothing held.
 * Congregational ceiling is about D5, so if a crowd is meant to sing along,
 * transpose back to G rather than using this.
 */
export const OLD_100TH: Arrangement = {
  id: 'old-100th',
  title: 'Doxology (OLD 100TH)',
  key: 'A major',
  beatsPerBar: 4,
  defaultBpm: 60,
  totalBeats: 42,

  source:
    'CPDL #02714, ed. John Henry Fowler, from the Genevan Psalter (1551). ' +
    'Four discrete SATB parts, extracted from the edition MusicXML.',
  verifiedAgainst:
    'CPDL #21518, ed. Jennifer Lee (Public Domain), from "55 Songs and ' +
    'Choruses for Community Singing" (1917). All 32 soprano pitches identical.',
  license:
    'Tune 1551 and text 1695 are public domain. Source edition is offered ' +
    'under the CPDL licence, which permits free reuse with attribution.',

  parts: {
  soprano: [
    { midi: 69, startBeat: 0, beats: 1, lyric: "Praise" },
    { midi: 69, startBeat: 1, beats: 1, lyric: "God" },
    { midi: 68, startBeat: 2, beats: 1, lyric: "from" },
    { midi: 66, startBeat: 3, beats: 1, lyric: "whom" },
    { midi: 64, startBeat: 4, beats: 1, lyric: "all" },
    { midi: 69, startBeat: 5, beats: 1, lyric: "bless-" },
    { midi: 71, startBeat: 6, beats: 1, lyric: "ings" },
    { midi: 73, startBeat: 7, beats: 2, lyric: "flow" },
    { midi: 73, startBeat: 9, beats: 1, lyric: "Praise" },
    { midi: 73, startBeat: 10, beats: 1, lyric: "Him" },
    { midi: 73, startBeat: 11, beats: 1, lyric: "all" },
    { midi: 71, startBeat: 12, beats: 1, lyric: "crea-" },
    { midi: 69, startBeat: 13, beats: 1, lyric: "tures" },
    { midi: 74, startBeat: 14, beats: 1, lyric: "here" },
    { midi: 73, startBeat: 15, beats: 1, lyric: "be-" },
    { midi: 71, startBeat: 16, beats: 2, lyric: "low" },
    { midi: 69, startBeat: 18, beats: 1, lyric: "Praise" },
    { midi: 71, startBeat: 19, beats: 1, lyric: "Him" },
    { midi: 73, startBeat: 20, beats: 1, lyric: "a-" },
    { midi: 71, startBeat: 21, beats: 1, lyric: "bove" },
    { midi: 69, startBeat: 22, beats: 1, lyric: "ye" },
    { midi: 66, startBeat: 23, beats: 1, lyric: "heav'n-" },
    { midi: 68, startBeat: 24, beats: 1, lyric: "ly" },
    { midi: 69, startBeat: 25, beats: 2, lyric: "host" },
    { midi: 76, startBeat: 27, beats: 1, lyric: "Praise" },
    { midi: 73, startBeat: 28, beats: 1, lyric: "Fa-" },
    { midi: 69, startBeat: 29, beats: 1, lyric: "ther," },
    { midi: 71, startBeat: 30, beats: 1, lyric: "Son," },
    { midi: 74, startBeat: 31, beats: 1, lyric: "and" },
    { midi: 73, startBeat: 32, beats: 1, lyric: "Ho-" },
    { midi: 71, startBeat: 33, beats: 1, lyric: "ly" },
    { midi: 69, startBeat: 34, beats: 2, lyric: "Ghost" },
    { midi: 69, startBeat: 36, beats: 2, lyric: "A-" },
    { midi: 69, startBeat: 38, beats: 4, lyric: "men" },
  ],
  alto: [
    { midi: 64, startBeat: 0, beats: 1 },
    { midi: 64, startBeat: 1, beats: 1 },
    { midi: 64, startBeat: 2, beats: 1 },
    { midi: 61, startBeat: 3, beats: 1 },
    { midi: 61, startBeat: 4, beats: 1 },
    { midi: 61, startBeat: 5, beats: 1 },
    { midi: 64, startBeat: 6, beats: 1 },
    { midi: 64, startBeat: 7, beats: 2 },
    { midi: 64, startBeat: 9, beats: 1 },
    { midi: 64, startBeat: 10, beats: 1 },
    { midi: 69, startBeat: 11, beats: 1 },
    { midi: 68, startBeat: 12, beats: 1 },
    { midi: 69, startBeat: 13, beats: 1 },
    { midi: 69, startBeat: 14, beats: 1 },
    { midi: 69, startBeat: 15, beats: 1 },
    { midi: 68, startBeat: 16, beats: 2 },
    { midi: 69, startBeat: 18, beats: 1 },
    { midi: 68, startBeat: 19, beats: 1 },
    { midi: 69, startBeat: 20, beats: 1 },
    { midi: 68, startBeat: 21, beats: 1 },
    { midi: 64, startBeat: 22, beats: 1 },
    { midi: 66, startBeat: 23, beats: 1 },
    { midi: 64, startBeat: 24, beats: 1 },
    { midi: 64, startBeat: 25, beats: 2 },
    { midi: 64, startBeat: 27, beats: 1 },
    { midi: 64, startBeat: 28, beats: 1 },
    { midi: 69, startBeat: 29, beats: 1 },
    { midi: 68, startBeat: 30, beats: 1 },
    { midi: 66, startBeat: 31, beats: 0.5 },
    { midi: 68, startBeat: 31.5, beats: 0.5 },
    { midi: 69, startBeat: 32, beats: 1 },
    { midi: 68, startBeat: 33, beats: 1 },
    { midi: 69, startBeat: 34, beats: 2 },
    { midi: 66, startBeat: 36, beats: 2 },
    { midi: 64, startBeat: 38, beats: 4 },
  ],
  tenor: [
    { midi: 61, startBeat: 0, beats: 1 },
    { midi: 61, startBeat: 1, beats: 1 },
    { midi: 59, startBeat: 2, beats: 1 },
    { midi: 57, startBeat: 3, beats: 1 },
    { midi: 56, startBeat: 4, beats: 1 },
    { midi: 57, startBeat: 5, beats: 1 },
    { midi: 56, startBeat: 6, beats: 1 },
    { midi: 57, startBeat: 7, beats: 2 },
    { midi: 57, startBeat: 9, beats: 1 },
    { midi: 61, startBeat: 10, beats: 1 },
    { midi: 64, startBeat: 11, beats: 1 },
    { midi: 64, startBeat: 12, beats: 1 },
    { midi: 61, startBeat: 13, beats: 1 },
    { midi: 66, startBeat: 14, beats: 1 },
    { midi: 64, startBeat: 15, beats: 1 },
    { midi: 64, startBeat: 16, beats: 2 },
    { midi: 61, startBeat: 18, beats: 1 },
    { midi: 64, startBeat: 19, beats: 1 },
    { midi: 64, startBeat: 20, beats: 1 },
    { midi: 64, startBeat: 21, beats: 1 },
    { midi: 64, startBeat: 22, beats: 1 },
    { midi: 62, startBeat: 23, beats: 0.5 },
    { midi: 61, startBeat: 23.5, beats: 0.5 },
    { midi: 59, startBeat: 24, beats: 1 },
    { midi: 61, startBeat: 25, beats: 2 },
    { midi: 61, startBeat: 27, beats: 1 },
    { midi: 57, startBeat: 28, beats: 1 },
    { midi: 61, startBeat: 29, beats: 1 },
    { midi: 64, startBeat: 30, beats: 1 },
    { midi: 66, startBeat: 31, beats: 1 },
    { midi: 64, startBeat: 32, beats: 1 },
    { midi: 64, startBeat: 33, beats: 0.5 },
    { midi: 62, startBeat: 33.5, beats: 0.5 },
    { midi: 61, startBeat: 34, beats: 2 },
    { midi: 62, startBeat: 36, beats: 2 },
    { midi: 61, startBeat: 38, beats: 4 },
  ],
  bass: [
    { midi: 57, startBeat: 0, beats: 1 },
    { midi: 57, startBeat: 1, beats: 1 },
    { midi: 52, startBeat: 2, beats: 1 },
    { midi: 54, startBeat: 3, beats: 1 },
    { midi: 49, startBeat: 4, beats: 1 },
    { midi: 54, startBeat: 5, beats: 1 },
    { midi: 52, startBeat: 6, beats: 1 },
    { midi: 45, startBeat: 7, beats: 2 },
    { midi: 57, startBeat: 9, beats: 1 },
    { midi: 57, startBeat: 10, beats: 1 },
    { midi: 57, startBeat: 11, beats: 1 },
    { midi: 52, startBeat: 12, beats: 1 },
    { midi: 54, startBeat: 13, beats: 1 },
    { midi: 50, startBeat: 14, beats: 1 },
    { midi: 45, startBeat: 15, beats: 1 },
    { midi: 52, startBeat: 16, beats: 2 },
    { midi: 54, startBeat: 18, beats: 1 },
    { midi: 52, startBeat: 19, beats: 1 },
    { midi: 57, startBeat: 20, beats: 1 },
    { midi: 52, startBeat: 21, beats: 1 },
    { midi: 49, startBeat: 22, beats: 1 },
    { midi: 50, startBeat: 23, beats: 1 },
    { midi: 52, startBeat: 24, beats: 1 },
    { midi: 45, startBeat: 25, beats: 2 },
    { midi: 57, startBeat: 27, beats: 1 },
    { midi: 57, startBeat: 28, beats: 1 },
    { midi: 54, startBeat: 29, beats: 1 },
    { midi: 52, startBeat: 30, beats: 1 },
    { midi: 47, startBeat: 31, beats: 1 },
    { midi: 49, startBeat: 32, beats: 0.5 },
    { midi: 50, startBeat: 32.5, beats: 0.5 },
    { midi: 52, startBeat: 33, beats: 1 },
    { midi: 45, startBeat: 34, beats: 2 },
    { midi: 50, startBeat: 36, beats: 2 },
    { midi: 45, startBeat: 38, beats: 4 },
  ],
  },

  phrases: [
    { id: 'p1', short: 'Line 1', label: 'Praise God from whom all blessings flow', startBeat: 0, endBeat: 9 },
    { id: 'p2', short: 'Line 2', label: 'Praise Him all creatures here below', startBeat: 9, endBeat: 18 },
    { id: 'p3', short: 'Line 3', label: "Praise Him above ye heav'nly host", startBeat: 18, endBeat: 27 },
    { id: 'p4', short: 'Line 4', label: 'Praise Father, Son, and Holy Ghost', startBeat: 27, endBeat: 36 },
    { id: 'p5', short: 'Amen', label: 'Amen', startBeat: 36, endBeat: 42 },
  ],
};
