"use client";

export default function AIDisclaimer({ className = "" }: { className?: string }) {
  return (
    <div className={`rounded-lg border border-secondary/20 bg-secondary/5 px-4 py-3 text-xs text-muted ${className}`}>
      <span className="mr-1 font-medium text-secondary">AI Preview</span>
      This preview was generated by AI and may not perfectly represent the final
      product. We can&apos;t guarantee every design shown is possible to produce.
      We&apos;ll reach out if there are any issues with your order.
    </div>
  );
}
